
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}

baseurl: "/SentimentsOfSafetyNYCSubway" # the subpath of your site, replace with the name of the github repository where you will host your site
url: "" # the base hostname & protocol for your site, e.g. http://github-username.io

title: Sentiments of Safety on the New York City Subway
author: Erin Wen, Timothy Yoshimura Small
externallink: columbia.edu #can include an external url here
description:  >- # this means to ignore newlines until "baseurl:"
  A visual and analytical interrogation at the collision of policy, media, and public sentiment.


# Build settings - no need to change these

theme: minima
plugins:
  - jekyll-feed
